# Generated by Django 5.1.1 on 2024-09-29 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('liquidity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('buying_power', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForexPortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='OptionsPortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='RealEstatePortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.portfolio')),
            ],
            bases=('portfolio.portfolio',),
        ),
    ]
