# Generated by Django 5.1.1 on 2024-09-29 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.model'),
        ),
        migrations.AddField(
            model_name='modelcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.component'),
        ),
        migrations.AddField(
            model_name='modelcomponent',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.model'),
        ),
        migrations.AddField(
            model_name='model',
            name='components',
            field=models.ManyToManyField(through='developer.ModelComponent', to='developer.component'),
        ),
        migrations.AddField(
            model_name='connection',
            name='from_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='developer.modelcomponent'),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='developer.modelcomponent'),
        ),
    ]
