# Generated by Django 5.1.1 on 2024-09-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark')], default='LIGHT', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
            ],
        ),
    ]
